#pragma once

void test_transport_create_socket_should_initialize_receive_event();
void test_transport_create_socket_should_initialize_receive_event_data();
void test_transport_create_socket_should_add_receive_event_to_event_system();
