name: CI

on:
  push:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Clang Format'
      uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        extensions: 'h,cpp,c'
        clangFormatVersion: 16
        inplace: True

    - name: 'Ensure no changes'
      run: git diff --exit-code

    - name: Update package database
      run: sudo apt-get update

    - name: Install libopaque dependencies
      run: sudo apt-get install libsodium-dev pkgconf

    - name: Install valgrind
      run: sudo apt-get install valgrind

    - name: Install vcpkg and dependencies
      run: git submodule update --init && ./vcpkg/bootstrap-vcpkg.sh --disableMetrics

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_RASTA_GRPC_BRIDGE=ON -DENABLE_RASTA_TLS=ON -DENABLE_RASTA_OPAQUE=ON --preset vcpkg

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -v

    - name: Rcat UDP Test
      run: cd ${{github.workspace}} && ./examples/example_scripts/example_udp.sh
      timeout-minutes: 1

    - name: Rcat TCP Test
      run: cd ${{github.workspace}} && ./examples/example_scripts/example_tcp.sh
      timeout-minutes: 1

    - name: Rcat TLS Test
      run: cd ${{github.workspace}} && ./examples/example_scripts/example_tls.sh
      timeout-minutes: 1

    - name: Rcat DTLS Test
      run: cd ${{github.workspace}} && ./examples/example_scripts/example_dtls.sh
      timeout-minutes: 1

    - name: Rcat KEX / Opaque Test
      run: cd ${{github.workspace}} && ./examples/example_scripts/example_kex.sh

    - name: CTest
      run: cd ${{github.workspace}}/build && ctest . --output-on-failure

    - name: Valgrind Memcheck
      run: cd ${{github.workspace}}/build && ctest . -T memcheck --output-on-failure

    - name: Configure CMake without extensions
      # force full rebuild, but keep installed dependencies
      run: find ${{github.workspace}}/build | grep -v "vcpkg_installed" | xargs rm && cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_RASTA_GRPC_BRIDGE=ON -DENABLE_RASTA_TLS=ON --preset vcpkg

    - name: Build without extensions
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Rcat UDP Test without extensions
      run: cd ${{github.workspace}} && ./examples/example_scripts/example_udp.sh
      timeout-minutes: 1

    - name: Rcat TCP Test without extensions
      run: cd ${{github.workspace}} && ./examples/example_scripts/example_tcp.sh
      timeout-minutes: 1

    - name: Rcat TLS Test without extensions
      run: cd ${{github.workspace}} && ./examples/example_scripts/example_tls.sh
      timeout-minutes: 1

    - name: Rcat DTLS Test without extensions
      run: cd ${{github.workspace}} && ./examples/example_scripts/example_dtls.sh
      timeout-minutes: 1

    - name: CTest without extensions
      run: cd ${{github.workspace}}/build && ctest . --output-on-failure
